FROM node:12 as build

COPY . /srv
WORKDIR /srv/
RUN yarn && yarn build && yarn export

# Stage - Production
FROM nginx:1.17-alpine
COPY --from=build /srv/out /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
