FROM node:12

RUN apt-get update \
    && apt-get install -y chromium libatk-bridge2.0-0 libxkbcommon-x11-0 libgbm1 libgtk-3-0 --no-install-recommends

COPY . /srv

WORKDIR /srv/

RUN yarn && yarn build

EXPOSE 5300

CMD ["yarn", "start"]
