name: Format Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install Python dependencies
        run: make -C python install-dev
      - name: Format with ruff
        run: python/.venv/bin/python -m ruff format --check
      - name: Format database package
        working-directory: database
        run: yarn && yarn run prettier . --check
      - name: Format frontend package
        working-directory: frontend
        run: yarn && yarn run prettier . --check
      - name: Format proxy package
        working-directory: proxy
        run: yarn && yarn run prettier . --check
